#%RAML 1.0
title: exp-alpha-zab-salesforce-api


types:

  

traits:
  client-id-required: !include /exchange_modules/068df3a6-ddea-4094-b31f-87b18dfd0204/client-id-enforcement/1.0.0/client-id-enforcement.raml
  transaction-header: !include /exchange_modules/068df3a6-ddea-4094-b31f-87b18dfd0204/transaction-header/1.0.0/transaction-header.raml

uses:
  cd: /exchange_modules/068df3a6-ddea-4094-b31f-87b18dfd0204/common-data-types/1.0.0/common-data-types.raml
  errors: /library/error-responses.raml

/upsertportaluser:
  patch:
    is: [client-id-required, errors.errorResponses]
    description: update portal user
    body:
      application/json:
    responses:
      200:
        description: success
        body:
          application/json:
            example:
              result: "success"


/createsubscription:
    post:
      is: [client-id-required, errors.errorResponses]
      description: create subscription
      body:
        application/json:
      responses:
        200:
          description: success
          body:
            application/json:
              example:
                result: "success"

/updatesubscription:
    patch:
      is: [client-id-required, errors.errorResponses]
      description: update subscription 
      body:
        application/json:
      responses:
        200:
          description: success
          body:
            application/json:
              example:
                result: "success"

/eula-acceptance:
  put:
    is: [client-id-required, errors.errorResponses]
    description: update subscription
    body:
      application/json:
    responses:
      200:
        description: success
        body:
          application/json:
            example:
                result: "success"