name: CI/CD - MuleSoft CloudHub EU1 (Build and Deploy Separate Jobs)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact-name: ${{ steps.set_output.outputs.artifact_name }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Mule Application
      run: mvn clean package -DmuleDeploy

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mule-app
        path: target/*.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: dev

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: mule-app
        path: target/

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Deploy to CloudHub EU1 via Maven
      env:
        ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
        ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        ANYPOINT_ENV: ${{ secrets.ANYPOINT_ENV }}
      run: mvn mule:deploy -Pcloudhub-deploy
