name: CI/CD - MuleSoft CloudHub EU1 Deployment (npm CLI v4)

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Java 11 for Mule builds
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Step 3: Build Mule Application (produces target/ci-cd-test-1.0.0-SNAPSHOT.zip)
    - name: Build Mule Application
      run: mvn clean package -DmuleDeploy

    # Step 4: Install Anypoint CLI v4 (via npm)
    - name: Install Anypoint CLI v4
      run: npm install -g anypoint-cli-v4

    # Step 5: Deploy Mule App to CloudHub EU1
    - name: Deploy Mule App to CloudHub EU1
      env:
        ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
        ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      run: |
        echo '{
          "applicationName": "ci-cd-test",
          "environment": "${{ secrets.ANYPOINT_ENV }}",
          "region": "eu1",
          "artifact": "target/ci-cd-test-1.0.0-SNAPSHOT.zip",
          "workers": 1,
          "workerType": "MICRO"
        }' > deploy-config.json

        anypoint-cli-v4 runtime-mgr cloudhub-application deploy --deploymentFile deploy-config.json
