name: CI/CD - MuleSoft CloudHub EU1 Deployment with JSON Config

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Mule App (Maven Package)
      run: mvn clean package -DmuleDeploy

    - name: Install Anypoint CLI v4
      run: npm install -g anypoint-cli-v4

    - name: Authenticate with Anypoint Platform
      run: |
        anypoint-cli-v4 config set client_id ${{ secrets.ANYPOINT_CLIENT_ID }}
        anypoint-cli-v4 config set client_secret ${{ secrets.ANYPOINT_CLIENT_SECRET }}

    - name: Deploy Mule App using JSON Deployment Config
      run: |
        echo '{
          "applicationName": "ci-cd-test",
          "environment": "${{ secrets.ANYPOINT_ENV }}",
          "region": "eu1",
          "artifact": "target/ci-cd-test-1.0.0-SNAPSHOT.zip",
          "workers": 1,
          "workerType": "MICRO"
        }' > deploy-config.json

        anypoint-cli-v4 runtime-mgr cloudhub-application deploy --deploymentFile deploy-config.json
