name: CI/CD MuleSoft Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DmuleDeploy

    - name: Install Anypoint CLI
      run: npm install -g anypoint-cli-v4

    - name: Authenticate with Anypoint Platform
      run: |
        anypoint-cli-v4 config set client_id ${{ secrets.ANYPOINT_CLIENT_ID }}
        anypoint-cli-v4 config set client_secret ${{ secrets.ANYPOINT_CLIENT_SECRET }}

    - name: Deploy to CloudHub
      run: |
        anypoint-cli-v4 runtime-mgr cloudhub-application deploy your-app-name \
          --file target/your-app-name-mule-application.jar \
          --environment ${{ secrets.ANYPOINT_ENV }} \
          --region eu1
