name: CI/CD - MuleSoft CloudHub EU1 Deployment (Correct CLI v4 Binary)

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Mule Application
      run: mvn clean package -DmuleDeploy

    - name: Download and Install Anypoint CLI v4
      run: |
        curl -L https://anypoint.mulesoft.com/cli/anypoint-cli-4.x.x-linux-x64.tar.gz -o anypoint-cli.tar.gz
        mkdir anypoint-cli
        tar -xzf anypoint-cli.tar.gz -C anypoint-cli
        echo "$(pwd)/anypoint-cli/bin" >> $GITHUB_PATH

    - name: Deploy Mule App to CloudHub EU1 (Using CLI Auth Flags)
      run: |
        echo '{
          "applicationName": "ci-cd-test",
          "environment": "${{ secrets.ANYPOINT_ENV }}",
          "region": "eu1",
          "artifact": "target/ci-cd-test-1.0.0-SNAPSHOT.zip",
          "workers": 1,
          "workerType": "MICRO"
        }' > deploy-config.json

        anypoint-cli-v4 --client-id "${{ secrets.ANYPOINT_CLIENT_ID }}" --client-secret "${{ secrets.ANYPOINT_CLIENT_SECRET }}" runtime-mgr cloudhub-application deploy --deploymentFile deploy-config.json
      env:
        ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
        ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
