name: CI/CD - MuleSoft Deployment to EU1

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Java 11 for Mule 4.x
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Step 3: Build the Mule Application (.zip output)
    - name: Build Mule application (Maven Package)
      run: mvn clean package -DmuleDeploy

    # Optional Step: Run MUnit Tests (if you have tests configured)
    - name: Run MUnit Tests
      run: mvn test || echo "MUnit tests failed, but continuing deployment"

    # Step 4: Install Anypoint CLI v4 (for CloudHub deployment)
    - name: Install Anypoint CLI v4
      run: npm install -g anypoint-cli-v4

    # Step 5: Authenticate to Anypoint Platform (using Connected App secrets)
    - name: Authenticate with Anypoint Platform
      run: |
        anypoint-cli-v4 config set client_id ${{ secrets.ANYPOINT_CLIENT_ID }}
        anypoint-cli-v4 config set client_secret ${{ secrets.ANYPOINT_CLIENT_SECRET }}

    # Step 6: Deploy the Mule application to CloudHub EU1
    - name: Deploy to CloudHub EU1
      run: |
        anypoint-cli-v4 runtime-mgr cloudhub-application deploy ci-cd-test \
          --artifact target/ci-cd-test-1.0.0-SNAPSHOT.zip \
          --environment ${{ secrets.ANYPOINT_ENV }} \
          --region eu1 \
          --workers 1 \
          --workerType MICRO

    # Optional: You can add post-deployment smoke tests here
