name: CI/CD - MuleSoft Deployment to CloudHub EU1 (CLI v4 2025)

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Mule Application
      run: mvn clean package -DmuleDeploy

    - name: Install Anypoint CLI v4
      run: npm install -g anypoint-cli-v4

    - name: Deploy to CloudHub EU1 using JSON Config
      env:
        ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
        ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      run: |
        echo '{
          "applicationName": "ci-cd-test",
          "environment": "${{ secrets.ANYPOINT_ENV }}",
          "region": "eu1",
          "artifact": "target/ci-cd-test-1.0.0-SNAPSHOT.zip",
          "workers": 1,
          "workerType": "MICRO"
        }' > deploy-config.json

        anypoint-cli-v4 runtime-mgr cloudhub-application deploy --deploymentFile deploy-config.json
