name: MuleSoft CI/CD - Build and Deploy to CloudHub (Manual Maven 3.6.3 Install)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Maven 3.6.3 Manually
        run: |
          MAVEN_VERSION=3.6.3
          wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          tar xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
          export MAVEN_HOME=$PWD/apache-maven-$MAVEN_VERSION
          echo "MAVEN_HOME=$MAVEN_HOME" >> $GITHUB_ENV
          echo "$MAVEN_HOME/bin" >> $GITHUB_PATH

      - name: Verify Maven Version
        run: mvn -version

      - name: Configure Maven settings.xml for Anypoint Exchange authentication
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
            <servers>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
                <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Deploy to CloudHub
        env:
          anypoint.username: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
          anypoint.password: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
        run: |
          mvn clean deploy \
            -DskipTests \
            -Danypoint.username=$ANYPOINT_USERNAME \
            -Danypoint.password=$ANYPOINT_PASSWORD \
            -Danypoint.environment=Sandbox \
            -Dmule.application.name=exp-alpha-zab-salesforce-api
